### ISSUE TITLE
Bug in `sign_changes_at`

### ISSUE THREAD

**Issue by hamarb123** [programmerjake/algebraics#4]
https://github.com/programmerjake/algebraics/blob/196e8991ef98b336ed0149e6a28254e3673a0d4c/src/algebraic_numbers.rs#L201-L208

This section should actually be something like:
```rust
ValueOrInfinity::NegativeInfinity => {
    let degree = polynomial.degree().unwrap_or(0);
    if degree.is_odd() {
        Sign::new(&-polynomial.highest_power_coefficient())
    } else {
        Sign::new(&polynomial.highest_power_coefficient())
    }
}
```

I ran into this bug when copying this section of code.
I can make a PR if you'd like.

**Comment by programmerjake** [comment]
feel free to make a PR
